#!/usr/bin/env bash
# HailBytes — Terraform remote state bootstrap for AWS.
#
# Creates the S3 bucket Terraform keeps its state in, and writes the backend.tf
# that points at it. Run it BEFORE the first apply of each deployment; every
# deployment in the same account and region shares the bucket, each under its
# own --key.
#
#   ./quickstart/bootstrap-state-aws.sh --out . --key clients/acme/sat-ha.tfstate
#
# Options (or the matching environment variable):
#   --out DIR       HB_OUT          where to write backend.tf (default: cwd)
#   --region R      AWS_REGION      region for the bucket     (default us-east-1)
#   --bucket NAME   HB_STATE_BUCKET state bucket (default hailbytes-tfstate-<account>-<region>)
#   --key NAME      HB_STATE_KEY    state object              (default hailbytes.tfstate)
#   --print-only                    print backend.tf, create nothing
#
# WHY THIS EXISTS
# `terraform init` with no backend keeps state in the working directory, which
# in AWS CloudShell lives in a home directory that is deleted after a period of
# inactivity. A deployment whose state is gone keeps running -- and billing --
# with nothing describing it. This is the AWS twin of bootstrap-state-azure.sh.
#
# The bucket is configured for that job specifically:
#
#   versioning              a bad state write can be rolled back to the version
#                           before it, which is the only cheap undo Terraform has
#   encryption at rest      SSE-S3; state holds resource IDs, generated
#                           passwords and the quickstarts' self-signed TLS key
#   public access blocked   all four Block Public Access settings on
#   TLS-only bucket policy  requests without TLS are denied
#   bucket-owner ownership  ACLs disabled, so nothing can grant access sideways
#
# Locking uses S3's native lock file (use_lockfile), so there is no DynamoDB
# table to create or pay for. That needs Terraform 1.10 or newer.
#
# ON REPEAT RUNS this is idempotent: an existing bucket is reused and its
# settings re-applied, so it is safe to re-run for each new client.

set -uo pipefail

OUT="${HB_OUT:-$PWD}"
REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-us-east-1}}"
BUCKET="${HB_STATE_BUCKET:-}"
KEY="${HB_STATE_KEY:-hailbytes.tfstate}"
PRINT_ONLY=0

while [ $# -gt 0 ]; do
    case "$1" in
        --out)        [ $# -ge 2 ] || { echo "--out needs a value" >&2; exit 2; }; OUT="$2"; shift ;;
        --out=*)      OUT="${1#--out=}" ;;
        --region)     [ $# -ge 2 ] || { echo "--region needs a value" >&2; exit 2; }; REGION="$2"; shift ;;
        --region=*)   REGION="${1#--region=}" ;;
        --bucket)     [ $# -ge 2 ] || { echo "--bucket needs a value" >&2; exit 2; }; BUCKET="$2"; shift ;;
        --bucket=*)   BUCKET="${1#--bucket=}" ;;
        --key)        [ $# -ge 2 ] || { echo "--key needs a value" >&2; exit 2; }; KEY="$2"; shift ;;
        --key=*)      KEY="${1#--key=}" ;;
        --print-only) PRINT_ONLY=1 ;;
        -h|--help)
            sed -n '/^#   \.\/quickstart\/bootstrap-state-aws\.sh/,/^#   --print-only/p' "${BASH_SOURCE[0]}" \
                | sed 's/^# \{0,1\}//'
            exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
    shift
done

ok()   { printf '  ok    %s\n' "$*"; }
note() { printf '        %s\n' "$*"; }
die()  { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

backend_tf() {
    cat <<EOF
# Generated by quickstart/bootstrap-state-aws.sh.
#
# Terraform keeps its state in the S3 object below rather than in this
# directory, so it survives this shell and this CloudShell session. Commit this
# file: it contains no secret, and losing it means the next 'terraform init'
# starts from empty state and proposes to create what already exists.
terraform {
  backend "s3" {
    bucket  = "${BUCKET}"
    key     = "${KEY}"
    region  = "${REGION}"
    encrypt = true

    # S3-native state locking. Requires Terraform 1.10 or newer.
    use_lockfile = true
  }
}
EOF
}

if [ "$PRINT_ONLY" -eq 1 ]; then
    [ -n "$BUCKET" ] || die "--print-only needs --bucket (nothing is read, so no name can be derived)."
    backend_tf
    exit 0
fi

command -v aws >/dev/null || die "aws CLI not found."

# Mandatory: every check below reads AWS to decide whether to create something,
# and a read that silently fails would look like "does not exist".
ACCOUNT="$(aws sts get-caller-identity --query Account --output text 2>&1)" || {
    printf 'ERROR: cannot read the AWS identity.\n' >&2
    printf '%s\n' "$ACCOUNT" | sed 's/^/       /' >&2
    printf '       In CloudShell you are already signed in; elsewhere run aws configure or aws sso login.\n' >&2
    exit 1
}
[ -n "$BUCKET" ] || BUCKET="hailbytes-tfstate-${ACCOUNT}-${REGION}"

printf 'Terraform state backend\n'
note "account  ${ACCOUNT}"
note "region   ${REGION}"
note "bucket   ${BUCKET}"
note "key      ${KEY}"

if aws s3api head-bucket --bucket "$BUCKET" --region "$REGION" >/dev/null 2>&1; then
    ok "bucket ${BUCKET} already exists"
else
    # us-east-1 is the one region that refuses an explicit LocationConstraint.
    if [ "$REGION" = us-east-1 ]; then
        create=(aws s3api create-bucket --bucket "$BUCKET" --region "$REGION")
    else
        create=(aws s3api create-bucket --bucket "$BUCKET" --region "$REGION"
                --create-bucket-configuration "LocationConstraint=${REGION}")
    fi
    "${create[@]}" >/dev/null || die "could not create bucket ${BUCKET}. Names are global -- pass --bucket with another."
    ok "created bucket ${BUCKET}"
fi

aws s3api put-public-access-block --bucket "$BUCKET" --region "$REGION" \
    --public-access-block-configuration \
    BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true \
    && ok "public access blocked" || note "could not set Block Public Access"
aws s3api put-bucket-ownership-controls --bucket "$BUCKET" --region "$REGION" \
    --ownership-controls 'Rules=[{ObjectOwnership=BucketOwnerEnforced}]' \
    && ok "ACLs disabled" || note "could not set bucket ownership controls"
aws s3api put-bucket-versioning --bucket "$BUCKET" --region "$REGION" \
    --versioning-configuration Status=Enabled \
    && ok "versioning on" || note "could not enable versioning -- a bad state write could not be rolled back"
aws s3api put-bucket-encryption --bucket "$BUCKET" --region "$REGION" \
    --server-side-encryption-configuration \
    '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"},"BucketKeyEnabled":true}]}' \
    && ok "encryption at rest on" || note "could not set default encryption"
policy="$(printf '{"Version":"2012-10-17","Statement":[{"Sid":"DenyInsecureTransport","Effect":"Deny","Principal":"*","Action":"s3:*","Resource":["arn:aws:s3:::%s","arn:aws:s3:::%s/*"],"Condition":{"Bool":{"aws:SecureTransport":"false"}}}]}' "$BUCKET" "$BUCKET")"
aws s3api put-bucket-policy --bucket "$BUCKET" --region "$REGION" --policy "$policy" \
    && ok "TLS-only policy applied" || note "could not apply the TLS-only bucket policy"

mkdir -p "$OUT" || die "cannot write to ${OUT}"
if [ -f "${OUT}/backend.tf" ] && ! cmp -s <(backend_tf) "${OUT}/backend.tf"; then
    cp "${OUT}/backend.tf" "${OUT}/backend.tf.bak"
    note "existing backend.tf differed -- previous copy kept as backend.tf.bak"
fi
backend_tf > "${OUT}/backend.tf" || die "cannot write ${OUT}/backend.tf"
ok "wrote ${OUT}/backend.tf"

printf '\nNext:\n'
note "  cd ${OUT} && terraform init"
note "Needs Terraform 1.10+ for use_lockfile. Check with: terraform version"
note "Commit backend.tf. Losing it means the next init starts from empty state."
