#!/usr/bin/env bash
# HailBytes — Terraform remote state bootstrap for Azure.
#
# Creates the storage account Terraform keeps its state in, and writes the
# backend.tf that points at it. Run this ONCE per deployment, BEFORE the first
# apply.
#
#   ./quickstart/bootstrap-state-azure.sh --out ~/hailbytes-deploy
#
# Options (or the matching environment variable):
#   --out DIR           HB_OUT            where to write backend.tf (default: cwd)
#   --resource-group N  HB_STATE_RG       state resource group   (default tfstate-rg)
#   --location LOC      HB_LOCATION       region                 (default northeurope)
#   --account NAME      HB_STATE_ACCOUNT  storage account        (default: generated)
#   --container NAME    HB_STATE_CONTAINER container             (default tfstate)
#   --key NAME          HB_STATE_KEY      state blob             (default hailbytes.tfstate)
#   --subscription ID   HB_SUBSCRIPTION_ID default: the current az context
#   --print-only                          print backend.tf, create nothing
#
# WHY THIS EXISTS
# `terraform init` with no backend block keeps state in the working directory.
# In Azure Cloud Shell that directory only survives if the session has a storage
# account mounted; an ephemeral session discards it, and the deployment then
# carries on running with nothing describing it. Re-adopting it afterwards means
# importing every resource one at a time -- see docs/AZURE_STATE_RECOVERY.md.
#
# The account this creates is configured for that job specifically:
#
#   blob versioning        a bad state write can be rolled back to the version
#                          before it, which is the only cheap undo Terraform has
#   shared keys DISABLED   the access key is a bearer credential for all of your
#                          infrastructure state; Entra auth is per-identity and
#                          revocable, so the backend uses use_azuread_auth
#   no public blob access  state contains resource IDs, hostnames and, for some
#                          providers, secrets
#   CanNotDelete lock      on the resource group, because losing the state
#                          account is the failure this script exists to prevent
#
# Blob leases give Terraform state locking with no extra infrastructure, so
# concurrent applies are handled by the backend itself.
#
# ON REPEAT RUNS this is idempotent: an existing account, container or lock is
# reused rather than recreated, so it is safe to re-run to regenerate backend.tf.

set -uo pipefail

OUT="${HB_OUT:-$PWD}"
STATE_RG="${HB_STATE_RG:-tfstate-rg}"
LOCATION="${HB_LOCATION:-northeurope}"
ACCOUNT="${HB_STATE_ACCOUNT:-}"
CONTAINER="${HB_STATE_CONTAINER:-tfstate}"
KEY="${HB_STATE_KEY:-hailbytes.tfstate}"
SUB="${HB_SUBSCRIPTION_ID:-}"
PRINT_ONLY=0

while [ $# -gt 0 ]; do
    case "$1" in
        --out)            [ $# -ge 2 ] || { echo "--out needs a value" >&2; exit 2; }; OUT="$2"; shift ;;
        --out=*)          OUT="${1#--out=}" ;;
        --resource-group) [ $# -ge 2 ] || { echo "--resource-group needs a value" >&2; exit 2; }; STATE_RG="$2"; shift ;;
        --resource-group=*) STATE_RG="${1#--resource-group=}" ;;
        --location)       [ $# -ge 2 ] || { echo "--location needs a value" >&2; exit 2; }; LOCATION="$2"; shift ;;
        --location=*)     LOCATION="${1#--location=}" ;;
        --account)        [ $# -ge 2 ] || { echo "--account needs a value" >&2; exit 2; }; ACCOUNT="$2"; shift ;;
        --account=*)      ACCOUNT="${1#--account=}" ;;
        --container)      [ $# -ge 2 ] || { echo "--container needs a value" >&2; exit 2; }; CONTAINER="$2"; shift ;;
        --container=*)    CONTAINER="${1#--container=}" ;;
        --key)            [ $# -ge 2 ] || { echo "--key needs a value" >&2; exit 2; }; KEY="$2"; shift ;;
        --key=*)          KEY="${1#--key=}" ;;
        --subscription)   [ $# -ge 2 ] || { echo "--subscription needs a value" >&2; exit 2; }; SUB="$2"; shift ;;
        --subscription=*) SUB="${1#--subscription=}" ;;
        --print-only)     PRINT_ONLY=1 ;;
        -h|--help)
            sed -n '/^#   \.\/quickstart\/bootstrap-state-azure\.sh/,/^#   --print-only/p' "${BASH_SOURCE[0]}" \
                | sed 's/^# \{0,1\}//'
            exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
    shift
done

say()  { printf '%s\n' "$*"; }
ok()   { printf '  ok    %s\n' "$*"; }
note() { printf '        %s\n' "$*"; }
die()  { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

az_() {
    if [ -n "$SUB" ]; then az "$@" --subscription "$SUB"; else az "$@"; fi
}

# The backend block. Emitted from one place so --print-only and the written
# file cannot drift apart.
backend_tf() {
    cat <<EOF
# Generated by quickstart/bootstrap-state-azure.sh.
#
# Terraform keeps its state in the blob below rather than in this directory, so
# it survives this shell, this machine and this Cloud Shell session. Commit
# this file: it contains no secret, and losing it means the next 'terraform
# init' starts from empty state and proposes to create what already exists.
terraform {
  backend "azurerm" {
    resource_group_name  = "${STATE_RG}"
    storage_account_name = "${ACCOUNT}"
    container_name       = "${CONTAINER}"
    key                  = "${KEY}"

    # Entra ID rather than the account's shared key, which is disabled on this
    # account. Whoever runs terraform needs Storage Blob Data Contributor on
    # the account; this script grants it to the identity that ran it.
    use_azuread_auth = true
  }
}
EOF
}

if [ "$PRINT_ONLY" -eq 1 ]; then
    [ -n "$ACCOUNT" ] || die "--print-only needs --account (nothing is created, so no name can be generated)."
    backend_tf
    exit 0
fi

command -v az >/dev/null || die "az CLI not found."

# Mandatory, and for the same reason sweep-azure.sh requires it: every check
# below reads Azure to decide whether to create something. A failed read that
# is not caught here renders as "does not exist", and the script would then try
# to create resources in a subscription it cannot see.
SUB_NAME="$(az account show ${SUB:+--subscription "$SUB"} --query name -o tsv 2>&1)" || {
    printf 'ERROR: cannot read the Azure subscription.\n' >&2
    printf '%s\n' "$SUB_NAME" | sed 's/^/       /' >&2
    printf "       In Cloud Shell you are normally already logged in; otherwise run 'az login'.\n" >&2
    exit 1
}
[ -n "$SUB" ] || SUB="$(az account show --query id -o tsv)"

# Storage account names are GLOBAL, 3-24 chars, lowercase alphanumerics only.
# A generated name is date-stamped plus a short random tail: the date makes it
# recognisable months later, the tail keeps a same-day second attempt from
# colliding with the first.
if [ -z "$ACCOUNT" ]; then
    ACCOUNT="hbtfstate$(date -u +%m%d)$(tr -dc 'a-z0-9' </dev/urandom | head -c 6)"
fi
case "$ACCOUNT" in
    *[!a-z0-9]*) die "storage account name '${ACCOUNT}' must be lowercase alphanumerics only." ;;
esac
[ ${#ACCOUNT} -ge 3 ] && [ ${#ACCOUNT} -le 24 ] || die "storage account name '${ACCOUNT}' must be 3-24 characters."

say ""
say "Terraform state bootstrap"
note "subscription  ${SUB_NAME}"
note "group         ${STATE_RG} (${LOCATION})"
note "account       ${ACCOUNT}"
note "container     ${CONTAINER}"
note "state blob    ${KEY}"
say ""

if az_ group show -n "$STATE_RG" >/dev/null 2>&1; then
    ok "resource group ${STATE_RG} already exists"
else
    az_ group create -n "$STATE_RG" -l "$LOCATION" -o none \
        || die "could not create resource group ${STATE_RG}."
    ok "created resource group ${STATE_RG}"
fi

if az_ storage account show -n "$ACCOUNT" -g "$STATE_RG" >/dev/null 2>&1; then
    ok "storage account ${ACCOUNT} already exists"
else
    # --allow-shared-key-access false is what makes use_azuread_auth necessary
    # rather than optional. It is deliberate: a shared key read out of this
    # account is a bearer credential for the whole of your infrastructure state.
    az_ storage account create \
        --name "$ACCOUNT" --resource-group "$STATE_RG" --location "$LOCATION" \
        --sku Standard_LRS --kind StorageV2 \
        --min-tls-version TLS1_2 \
        --allow-blob-public-access false \
        --allow-shared-key-access false \
        --https-only true \
        -o none || die "could not create storage account ${ACCOUNT}. The name is global -- try --account with a different one."
    ok "created storage account ${ACCOUNT}"
fi

# Versioning is the rollback. Terraform writes state as a single blob, so a
# corrupt or truncated write has no other undo.
if az_ storage account blob-service-properties update \
    --account-name "$ACCOUNT" --resource-group "$STATE_RG" \
    --enable-versioning true -o none 2>/dev/null; then
    ok "blob versioning enabled"
else
    note "could not confirm blob versioning -- check it in the portal"
fi

# Data-plane RBAC. An Owner of the subscription is NOT automatically a data
# reader on a storage account, and with shared keys disabled there is no
# fallback: 'terraform init' would fail with a 403 that names the container and
# not the cause. So grant the identity running this script the data role now.
PRINCIPAL="$(az ad signed-in-user show --query id -o tsv 2>/dev/null)"
[ -n "$PRINCIPAL" ] || PRINCIPAL="$(az account show --query user.name -o tsv 2>/dev/null)"
SCOPE="/subscriptions/${SUB}/resourceGroups/${STATE_RG}/providers/Microsoft.Storage/storageAccounts/${ACCOUNT}"
if [ -n "$PRINCIPAL" ]; then
    if az_ role assignment create --role "Storage Blob Data Contributor" \
        --assignee "$PRINCIPAL" --scope "$SCOPE" -o none 2>/dev/null; then
        ok "granted Storage Blob Data Contributor to ${PRINCIPAL}"
    else
        ok "Storage Blob Data Contributor already held by ${PRINCIPAL}"
    fi
else
    note "could not identify the signed-in principal -- grant the data role by hand:"
    note "  az role assignment create --role 'Storage Blob Data Contributor' \\"
    note "    --assignee <you> --scope ${SCOPE}"
fi

# Role assignments are eventually consistent. Creating the container through
# the data plane immediately after the grant is the common way to see a 403 for
# a permission that was in fact just given, so retry rather than fail.
container_ready=0
for attempt in 1 2 3 4 5 6; do
    if az_ storage container show --name "$CONTAINER" --account-name "$ACCOUNT" \
        --auth-mode login >/dev/null 2>&1; then
        ok "container ${CONTAINER} already exists"; container_ready=1; break
    fi
    if az_ storage container create --name "$CONTAINER" --account-name "$ACCOUNT" \
        --auth-mode login -o none 2>/dev/null; then
        ok "created container ${CONTAINER}"; container_ready=1; break
    fi
    [ "$attempt" -eq 1 ] && note "waiting for the role assignment to propagate..."
    sleep 10
done
if [ "$container_ready" -eq 0 ]; then
    note "could not create the container -- the role assignment may still be propagating."
    note "Re-run this script in a minute; everything above it is already done."
fi

if az_ lock show --name protect-tfstate --resource-group "$STATE_RG" >/dev/null 2>&1; then
    ok "delete lock already present on ${STATE_RG}"
else
    if az_ lock create --name protect-tfstate --lock-type CanNotDelete \
        --resource-group "$STATE_RG" \
        --notes "Terraform state for HailBytes deployments. Removing this lock allows the state to be deleted." \
        -o none 2>/dev/null; then
        ok "delete lock applied to ${STATE_RG}"
    else
        note "could not apply the delete lock (needs Owner or User Access Administrator)"
    fi
fi

mkdir -p "$OUT" || die "cannot write to ${OUT}"
if [ -f "${OUT}/backend.tf" ] && ! cmp -s <(backend_tf) "${OUT}/backend.tf"; then
    cp "${OUT}/backend.tf" "${OUT}/backend.tf.bak"
    note "existing backend.tf differed -- previous copy kept as backend.tf.bak"
fi
backend_tf > "${OUT}/backend.tf" || die "cannot write ${OUT}/backend.tf"
ok "wrote ${OUT}/backend.tf"

say ""
say "Next:"
note "  cd ${OUT} && terraform init"
say ""
note "If state already exists locally in that directory, 'terraform init' offers"
note "to copy it to the new backend. Say yes -- that is the migration."
note "Commit backend.tf. Losing it means the next init starts from empty state."
say ""
